### ISSUE TITLE
HAXELIB_AUTH

### ISSUE THREAD

**Issue by kevinresol** [haxetink/tink_syntaxhub#10]
@back2dos please

**Comment by kevinresol** [comment]
https://travis-ci.com/haxetink/tink_syntaxhub/jobs/152722933#L524

hmmm, sth's wrong?

**Comment by kevinresol** [comment]
Correct example: https://travis-ci.org/haxetink/tink_core/jobs/438956545#L426
Incorrect: https://travis-ci.com/haxetink/tink_syntaxhub/jobs/152722933#L436

**Comment by back2dos** [comment]
I guess https://github.com/haxetink/tink_syntaxhub/commit/5d02d0ae7a92c743eba11280595b83686d3bcb5e fixes it?

**Comment by kevinresol** [comment]
Nope...

**Comment by kevinresol** [comment]
The var name is wrong, shown [here](https://travis-ci.com/haxetink/tink_syntaxhub/jobs/152722933#L436)

I think maybe you have a typo in the repo name or something?

**Comment by back2dos** [comment]
Ok, still don't understand what went wrong, but it seems to be working now ^^
