### ISSUE TITLE
Proposal to fix `main` interpolation using `--run`

### ISSUE THREAD

**Issue by 0b1kn00b** [haxetink/tink_syntaxhub#16]
There's no way of parsing out the `main` function in this case <s>and so inserting some define earlier than the `Plugin.use()` call is a way of doing this.
I can rewrite [stx_bake](https://github.com/ohmrun/stx_bake/) to be zero dependency and then syntaxhub can use some define (if it doesn't exist already and I just don't know) so that tink_runloop actually triggers properly. </s>
What say you?

**Comment by 0b1kn00b** [comment]
I can't find any way whatsoever around this so I've made an issue at the haxe repo.
https://github.com/HaxeFoundation/haxe/issues/11085

**Comment by back2dos** [comment]
Fixed via https://github.com/haxetink/tink_syntaxhub/commit/da0081b6b540ef13f207e6089cd4b9c74c37c92b
