### ISSUE TITLE
tink_await is called twice for each "@await" marked class

### ISSUE THREAD

**Issue by AdrianV** [haxetink/tink_syntaxhub#19]
in Haxe 4.3(.1)  - same as https://github.com/haxetink/tink_await/issues/48

I tried to get further with this problem and found these lines in SyntaxHub.hx
https://github.com/haxetink/tink_syntaxhub/blob/b6ea4966bbdee4d176ac8dd5d2d8ae3b362b2f86/src/tink/SyntaxHub.hx#L20-L23
actual the assignment `registered = true;`  makes no sense and I don't know what the original thought was, but when I change the code to 
```haxe
    if (registered) {
      return;
    }
    registered = true;
```

my problem goes away. Could someone please check if this is correct ?

**Comment by back2dos** [comment]
🤦

**Comment by AdrianV** [comment]
thanks :)
