### ISSUE TITLE
Problems with "--macro include('pack')"

### ISSUE THREAD

**Issue by kevinresol** [haxetink/tink_syntaxhub#5]
When using tink_await I encountered a problem, that SyntaxHub's class crawler does not process those macro included class. (verified by putting a `trace(c.target)` [here](https://github.com/haxetink/tink_await/blob/5959a97bd4dac069609e0d0c4cb9b55359f9a6e5/src/tink/await/Await.hx#L24)). Removing the macro made it work.

I tried to reproduce it in a minimal code base but was unsuccessful.
So I am going to just open an issue here and see if @back2dos or anyone can give some insights.

**Comment by back2dos** [comment]
This is an ordering issue. Calling `--macro include('pack')` will [eagerly type](https://github.com/HaxeFoundation/haxe/blob/d05ba02a196fb7b5633959276663ad6deec026c5/std/haxe/macro/Compiler.hx#L203) the modules in question. If this happens before `tink.SyntaxHub.use()` has had a chance to run, those types will not be processed. 

If you make sure that the include call is *after* all `-lib` args, then it should work.
